### ISSUE TITLE
Read Only item property

### ISSUE THREAD

**Issue by mohmedsaber** [rafael-trevisan/apex-plugin-simple_checkbox#1]
Great work.

can you add Read Only item property plz.

**Comment by rafael-trevisan** [comment]
Hey @mohmedsaber,

Thanks for the feedback.

I'll add this! In the meantime, I've already added "Printer Friendly" and "Read Only" modes in the [Peekaboo Simple Checkbox](https://github.com/rafael-trevisan/apex-plugin-peekaboo), which is the **exact** Simple Checkbox **plus** a nice built-in visibility setting. Take a look at it while I implement this feature here.

Cheers
— Rafael Trevisan

**Comment by rafael-trevisan** [comment]
All right @mohmedsaber,

"Read Only" property has been implemented here [v18.2.0](https://github.com/rafael-trevisan/apex-plugin-simple_checkbox/releases/tag/v18.2.0)

Cheers
— Rafael Trevisan

**Comment by mohmedsaber** [comment]
Great.
keep up the good work. 

and thanks for your valuable contribution to the APEX community.
