### ISSUE TITLE
No working

### ISSUE THREAD

**Issue by ghost** [rafael-trevisan/apex-plugin-simple_checkbox#2]
Hello, the plugin on simple mode is very good but it's not working on interactive grids. You can solve this??

**Comment by rafael-trevisan** [comment]
Hey @jfernal, hold tight there... I’m already testing it on IG and it’s almost ready to go.

**Comment by rafael-trevisan** [comment]
Hey @jfernal, here's the Simple Checkbox plugin for Interactive Grid.

https://github.com/rafael-trevisan/apex-plugin-ig_simple_checkbox

Hope you enjoy it.

Cheers

**Comment by ghost** [comment]
Woow... very good work rafael.... Congratulations.... and thank you very much for this plugin..!!!

**Comment by rafael-trevisan** [comment]
👍🏻
